### ISSUE TITLE
各ページのUrlがテンプレートのままですので、追って修正していきます。

### ISSUE THREAD

**Issue by mapconcierge** [gsc-aoyama/www4i18n#2]
各ページのUrlがテンプレートのままですので、追って修正していきます。

**Comment by mapconcierge** [comment]
Topページ
現在：https://gsc-aoyama.github.io/www4i18n/
修正：https://gsc-aoyama.github.io/international/
 
About Us
現在：https://gsc-aoyama.github.io/www4i18n/introduction/
修正：https://gsc-aoyama.github.io/international/aboutus/
 
About AGU
現在：https://gsc-aoyama.github.io/www4i18n/teacher/
修正：https://gsc-aoyama.github.io/international/aboutagu/
 
Exchange Student Program
現在：https://gsc-aoyama.github.io/www4i18n/campus/
修正：https://gsc-aoyama.github.io/international/exchange/
 
Extracurricular Program
現在：https://gsc-aoyama.github.io/www4i18n/studyabroad/
修正：https://gsc-aoyama.github.io/international/extracurricular/
 
Student Support
現在：https://gsc-aoyama.github.io/www4i18n/career/
修正：https://gsc-aoyama.github.io/international/support/
 
この他にも、URLに”www4i18n”を使用している場合、全て”international”に置き換えてください。

**Comment by mapconcierge** [comment]
- Backup ブランチ作成
https://github.com/gsc-aoyama/www4i18n/tree/backup_2019-07-19

**Comment by mapconcierge** [comment]
変更作業MEMO

1) GitHub Desktop でリポジトリのクローンを自分のPC側に作成して、フォルダ名を introduction から aboutus に改名。
https://github.com/gsc-aoyama/www4i18n/commit/5f44add87b6f1ecb7b73cb3eef4870cfddf4b7af

2) 設定ファイル _config.yml の中にある header_pages: 項目を   - pages/aboutus/index.md のように変更。
https://github.com/gsc-aoyama/www4i18n/commit/87a57ef50c8f84c2a1fcb5385774e51d48dfe3c4

**Comment by mapconcierge** [comment]
teacher → aboutagu 変更
https://github.com/gsc-aoyama/www4i18n/commit/a48b3b74fe8ba0197e2a37fefe2fc79f818d3e57

**Comment by mapconcierge** [comment]
* [x] teache → exchange 変更
https://github.com/gsc-aoyama/www4i18n/commit/dae0c481a583a12f6dfeca0604bebad5de7c75a0

* [x] 変更反映確認
https://gsc-aoyama.github.io/www4i18n/exchange/

**Comment by mapconcierge** [comment]
* [ ] studyabroad →extracurricular

* [ ] 変更反映確認

**Comment by mapconcierge** [comment]
* [ ] career → support

* [ ] 変更反映確認

**Comment by mapconcierge** [comment]
各カテゴリごとの名称変更は完了。

次のステップは DNSの変更のみです。 ＞ @lilysan 
DNSの切り替えは今夜、トラブルの起きにくい夜中に行う予定です。

**Comment by mapconcierge** [comment]
https://github.com/gsc-aoyama/www4i18n/issues/20 とも関連。

**Comment by mapconcierge** [comment]
* [ ] CNAMEファイルをレポジトリに追加
http://international.gsc.aoyama.ac.jp/

* [ ] DNSの設定として CNAME レコード追加(internal)

* [ ] DNSの設定として CNAME レコード追加(external)



http://international.gsc.aoyama.ac.jp/

**Comment by mapconcierge** [comment]
* [ ] International ページの URL 変更に合わせてメインサイトのヘッダーからもリンクを修正。
https://github.com/gsc-aoyama/www4gsc/commit/f73e770573574053665efee1662b8d6ad226d58d

**Comment by mapconcierge** [comment]
すべての変更作業を終えました。 ＞ @lilysan

**Comment by lilysan** [comment]
exchangeタブ内のPDFのリンク先を変更

**Comment by lilysan** [comment]
PDFリンク先を修正しました。
http://international.gsc.aoyama.ac.jp/exchange/

**Comment by mapconcierge** [comment]
ありがとうございます！！
確認しました。パーフェクトです！ ＞ @lilysan 

https://github.com/gsc-aoyama/www4i18n/commit/4362ec9994ae3bae64e61152a09d7487ad69beed

**Comment by mapconcierge** [comment]
閉じます！！
