### ISSUE TITLE
サイトページURLが https://gsc-aoyama.github.io/www4i18n/ と丸見え

### ISSUE THREAD

**Issue by mapconcierge** [gsc-aoyama/www4i18n#20]
https://gsc-aoyama.github.io/www4i18n/

**Comment by mapconcierge** [comment]
サイトページURLが https://gsc-aoyama.github.io/www4i18n/ と丸見えなので
*.gsc.aoyama.ac.jp サブドメインを割り当てる。

どんなサブドメインが良いか？

**Comment by mapconcierge** [comment]
＞ @ayaishizuka 
 https://int.gsc.aoytana.ac.jp

**Comment by ayaishizuka** [comment]
@mapconcierge 先生、
https://int.gsc.aoyama.ac.jp でお願いします。

**Comment by mapconcierge** [comment]
最終的に、このように対応しました。閉じます！
https://github.com/gsc-aoyama/www4i18n/issues/2
