### ISSUE TITLE
Home（トップページ）文言修正 

### ISSUE THREAD

**Issue by ayaishizuka** [gsc-aoyama/www4i18n#4]
- [x] トップページ写真の文言　Learning Beyond Boundaries. Collaboration Beyond Differences の最後に「.」(ピリオド）を足す。

- [ ] "The School of Global Studies and Collaboration (GSC) was established in 2015 with the goal of cultivating students' intellectual capacity and leadership to thrive in a rapidly changing global world." 以下の差し替える：
Our new pamphlet will be available soon.

**Comment by mapconcierge** [comment]
修正しました！
https://github.com/gsc-aoyama/www4i18n/commit/12b2a35c77212b3c45f06e227e4bc159297875d8
