### ISSUE TITLE
フッターの文言修正

### ISSUE THREAD

**Issue by ayaishizuka** [gsc-aoyama/www4i18n#5]
- 地球儀の下The School of Global Studies and Collaboration (GSC), AoyamaGakuin University のAoyamaとGakuinの間にスペースを足す

- ZIP: 252-5258を消す

- ©の文言はThe School of Global Studies and Collaboration (GSC), Aoyama Gakuin University, CC BY-NC-SA 4.0 となるようにGSCとAoyamaの順を入れ替える

**Comment by mapconcierge** [comment]
修正だん

https://github.com/gsc-aoyama/www4i18n/commit/8d96cddebf12c68c99605cc0c330b35f52612ea9
