### ISSUE TITLE
メニューバーiPhone対応の修正

### ISSUE THREAD

**Issue by ayaishizuka** [gsc-aoyama/www4i18n#6]
携帯端末で閲覧すると下にスクロールする際に左側のメニューが表示され、コンテンツの文字と被るので、メニューをクリックしない限りメニュー内容が表示されないように修正が必要。（GSCのホームページではこの現象は起らない。）

**Comment by mapconcierge** [comment]
業者に連絡します。

**Comment by mapconcierge** [comment]
＞ @nkhrhr @yahsan2  確認お願いします！！
