### ISSUE TITLE
フッターのリンクを消す

### ISSUE THREAD

**Issue by ayaishizuka** [gsc-aoyama/www4i18n#7]
フッターにあるAccess, Site Policy, Contact, Sitemapは全て日本語ページに飛ぶので、これら項目を消す。

**Comment by mapconcierge** [comment]
Access マップを英語にする。

**Comment by mapconcierge** [comment]
* [ ]  Access  英語にする
* [ ]  Site Policy  消す
* [ ]  Contact 英語にする
* [ ]  Sitemap 消す

**Comment by mapconcierge** [comment]
対応しました！
